#### R script with functions for lipidome comparison ####

### Data handelling ###

my_theme <- theme_set(
  theme_minimal() +
    theme(plot.title = element_text(size=12, hjust = 0.5),
          axis.text.x = element_text(size = 8),
          # axis.title = element_text(size = 10),
          axis.title.x = element_text(size = 10, hjust = 0.5),
          axis.title.y = element_text(size = 10, hjust = 0.5),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 10))
)


#' Transpose data frame with sorrect row- and column names.
#' 
#' @description 
#' `pretty_transpose` transposes a data frame to a new data frame
#' @details 
#' This function takes a data frame, transposes it and sets the former first column as the column names. 
#' Row names are automatically generated by the data.table::transpose() function. 
#' @param input_df a data frame with character strings and numerics
#' @examples 
#' df <- as.data.frame(cbind(c("ID", "a", "b", "c", "d"), c("z", 1, 2, 3, 4), c("x", 5, 6, 7, 8)))
#' pretty_transpose(df)
pretty_transpose <- function(input_df){
  t_input_df <- data.table::transpose(as.data.table(input_df), make.names = 1)
  t_input_df <- as.data.frame(t_input_df)
  row.names(t_input_df) <- colnames(input_df[-1])
  t_input_df
}


#' Takes a data frame with specific rownames and extracts meta data from it
#' 
#' @description 
#' `SID_to_metadata` takes a data frame with rownames in the form of 
#' <experiment_treatment_biol.rep.nr_tech.rep.nr> 
#' and extracts meta data
#' @details 
#' This function takes the information saved in sample IDs of the form 
#' <experiment_treatment_biol.rep.nr_tech.rep.nr> and saves each 
#' part of the sample ID as a column of character strings. 
#' If one part is missing, the column is filled with NAs. 
#' @param input_df a data frame with character strings and numerics
#' @examples 
#' df <- as.data.frame(rbind(c(1, 2, 3, 4), c(5, 6, 7, 8)))
#' row.names(df) <- c("Ex1_Tr1_1_1", "Ex1_Tr1_1_2")
#' colnames(df) <- c("a", "b", "c", "d")
#' ndf <- SID_to_metadata(df); ndf
SID_to_metadata <- function(input_df){
  n_sep <- mean(stringr::str_count(row.names(input_df), "_"))
  meta_info <- read.table(text = row.names(input_df), sep = "_")
  
  if(n_sep == 2){
    biol_rep <- paste(meta_info$V1, meta_info$V2, sep = "_")
    treatment <- meta_info$V1
    input_df <- tibble::add_column(input_df, biol_replicate = biol_rep, .before = 1)
    input_df <- tibble::add_column(input_df, treatment = treatment, .before = 1)
    input_df <- tibble::add_column(input_df, experiment = NA, .before = 1)
  } else if(n_sep == 3){
    biol_rep <- paste(meta_info$V1, meta_info$V2, meta_info$V3, sep = "_")
    treatment <- meta_info$V2
    experiment <- meta_info$V1
    input_df <- tibble::add_column(input_df, biol_replicate = biol_rep, .before = 1)
    input_df <- tibble::add_column(input_df, treatment = treatment, .before = 1)
    input_df <- tibble::add_column(input_df, experiment = experiment, .before = 1)
  } else{
    print("Wrong format")
  }
}


#' Transform all columns with caracters of a data frame to factor
#' 
#' @description 
#' `character_to_factor` takes a data frame with character strings and numerics 
#' and transforms all columns with characters only to factor columns
#' @details
#' All the columns of a data frame that only have character strings in them
#' are transformed to factor columns.
#' @param input_df a data frame with character strings and numerics
#' @examples 
#' df <- as.data.frame(rbind(c("Ex1", "TR1", 1, 2, 3, 4), c("Ex1", "Tr2", 5, 6, 7, 8)))
#' row.names(df) <- c("1", "2")
#' colnames(df) <- c("Ex", "Tr", "a", "b", "c", "d")
#' character_to_factor(df)
character_to_factor <- function(input_df){
  for(i in 1:ncol(input_df)){
    if (!is.numeric(input_df[,i])){
      input_df[,i] <- factor(input_df[,i])
    }
  }
  new_df <- input_df
}


