my_theme <- theme_set(
  theme_minimal() +
    theme(plot.title = element_text(size=12, hjust = 0.5),
          axis.text.x = element_text(size = 8),
          # axis.title = element_text(size = 10),
          axis.title.x = element_text(size = 10, hjust = 0.5),
          axis.title.y = element_text(size = 10, hjust = 0.5),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 10))
)


### Principal component analysis

#' Scree plot with factoextra
#'
#' @description `scree_factoextra` takes a prcomp element and diplays the percentage of variance 
#' explained by the principal components in a barplot. 
#' @details This function takes a prcom element (i.e. an element generated by the base::prcomp function), 
#' and displays the percentage of variance explained by each principal component in a barplot. 
#' Additionally there is also a dot- and line graph. 
#' @param prcomp_element object of class prcomp. The base::prcomp function performs a principal component analysis. 
#' This is the object it returns. 
#' @param out_path string. Path to save plot to png. 
#' If out_path is empty, the plot is printed to the device.
#' @examples 
#' pca_iris <- prcomp(select_if(iris, is.numeric))
#' scree_factoextra(pca_iris, title = "Scree plot iris")
#' \dontrun
#' dir.create(paste(getwd(), "/examples", sep = ""), showWarnings = FALSE)
#' dir <- paste(getwd(), "/examples/iris", sep = "")
#' scree_factoextra(pca_iris, title = "Scree plot iris", out_path = dir)
scree_factoextra <- function(prcomp_element, title = "Scree plot", out_path = "none"){
  
  scree <- factoextra::fviz_eig(prcomp_element, 
                                barfill = viridis(n = 2)[2], 
                                barcolor = viridis(n = 2)[2], 
                                linecolor = "grey40") +
    labs(title = title) +
    # scale_shape_manual(values = rep(20, nlevels(wd$treatment), size = 1)) +
    my_theme # sets general apperance, label size and justification
  
  if(out_path != "none"){
    print(paste("Saving plot to ", out_path, "_screePlot.png", sep = ""))
    ggsave(paste(out_path, "_screePlot.png", sep = ""),
           plot = scree)
  }
  else{
    scree
  }
}

#' Biplot with factorextra
#' 
#' @description `biplot_factoextra` prints a biplot from a prcomp element. 
#' @details This function prints a biplot from a prcomp element. 
#' The points can be colored by group. Loadings are optionally displayed. 
#' @param prcomp_element object of class prcomp. The base::prcomp function performs a principal component analysis. 
#' This is the object it returns. 
#' @param groups vector. Groups to color by. Default = "none"
#' @param ellipse bool. Draw confidence ellipse arount the clusters of groups. Default = FALSE. 
#' @param loadings bool. Draw loadings arrows and labels. Default = FALSE
#' @param out_path string. Path to save plot to png. 
#' If out_path is empty, the plot is printed to the device.
#' @examples 
#' pca_iris <- prcomp(dplyr::select_if(iris, is.numeric))
#' iris_groups <- iris$Species
#' biplot_factoextra(pca_iris)
#' biplot_factoextra(pca_iris, 
#'                   groups = iris_groups, 
#'                   ellipse = TRUE, 
#'                   loadings = FALSE)
#' \dontrun
#' dir.create(paste(getwd(), "/examples", sep = ""), showWarnings = FALSE)
#' dir <- paste(getwd(), "/examples/iris", sep = "")
#' biplot_factoextra(pca_iris, 
#'                  groups = iris_groups, 
#'                  ellipse = TRUE, 
#'                  loadings = FALSE, 
#'                  out_path = dir)
biplot_factoextra <- function(prcomp_element, 
                              groups = "none", 
                              ellipse = FALSE, 
                              loadings = TRUE, 
                              out_path = "none"){
  
  biplot <- factoextra::fviz_pca_biplot(prcomp_element, 
                                        ## color by group
                                        habillage = groups, # a vector of groups by whicht to color
                                        ## labels
                                        label = "var", 
                                        labelsize = 2,
                                        repel = TRUE, # labels do not overlap
                                        col.var = "grey40",
                                        ## ellipses
                                        addEllipses = ellipse, 
                                        ellipse.type = "norm",
                                        ## legend
                                        legend.title = "Groups")   +
    scale_color_viridis(discrete = TRUE) +
    scale_fill_viridis(discrete = TRUE) +
    my_theme
  
  if(out_path != "none"){
    print(paste("Saving to ", out_path, "_biplot.png", sep = ""))
    ggsave(paste(out_path, "_biplot.png", sep = ""),
           plot = biplot)
  }
  else{
    biplot
  }
}


#' Scree plot with Rbase
#'
#' @description `scree_base` takes a prcomp element and diplays the percentage and the cummulative percentage of variance of variance 
#' explained by the principal components in a barplot. 
#' @details This function takes a prcomp element (i.e. an element generated by the base::prcomp function), 
#' and displays the percentage of variance and the cummulative percentage of variance explained by each principal component in a dot- and line graph. 
#' @param prcomp_element object of class prcomp. The base::prcomp function performs a principal component analysis. 
#' This is the object it returns. 
#' @param out_path string. Path to save plot to png. 
#' If out_path is empty, the plot is printed to the device.
#' @examples 
#' pca_iris <- prcomp(select_if(iris, is.numeric))
#' scree_base(pca_iris)
#' \dontrun
#' dir.create(paste(getwd(), "/examples", sep = ""), showWarnings = FALSE)
#' dir <- paste(getwd(), "/examples/iris", sep = "")
#' scree_base(pca_iris, out_path = dir)
scree_base <- function(prcomp_element, 
                       title = c("Scree plot", "Cummulative scree plot"), 
                       out_path = "none"){
  
  out_name <- paste(out_path, "_screePlot", ".png", sep = "")
  
  # variance explained by each pc
  var_pca <- prcomp_element$sdev ^ 2
  prop_of_variance <- var_pca / sum(var_pca)
  
  func <- function(){
    par(mfrow=c(1,2))
    plot(prop_of_variance, # scree plot to decide which PCs are used
         main = "", xlab ="", ylab ="",
         ylim=c(0 ,1),
         type = "b")
    title( main = title[1], cex.main = 0.9, font.main = 1, 
           cex.lab = 0.8, 
           xlab =" Principal Component ", 
           ylab =" Proportion of Variance Explained")
    
    plot(cumsum(prop_of_variance ), # scree plot to decide which PCs are used
         main = "", xlab ="", ylab ="",
         ylim=c(0 ,1),
         type="b")
    title( main = title[2], cex.main = 0.9, font.main = 1, 
           cex.lab = 0.8, 
           xlab ="Principal Component",
           ylab ="Cumulative Proportion of Variance Explained")
  }
  
  if(out_path != "none"){
    print(paste("Saving to ", out_name))
    png(filename = out_name)
    func()
    dev.off()
  }
  else{
    func()
  }
  
  
}


#' Biplot with ggplot2
#' 
#' @description `biplot_ggplot2` prints a biplot from a prcomp element. 
#' @details This function prints a biplot from a prcomp element. 
#' The points can be colored by group. Loadings are optionally displayed. 
#' @param prcomp_element object of class prcomp. The base::prcomp function performs a principal component analysis. 
#' This is the object it returns. 
#' @param groups vector. Groups to color by. Default = "none"
#' @param ellipse bool. Draw confidence ellipse arount the clusters of groups. Default = FALSE. 
#' @param loadings bool. Draw loadings arrows and labels. Default = FALSE
#' @param out_path string. Path to save plot to png. 
#' If out_path is empty, the plot is printed to the device.
#' @examples 
#' biplot_ggplot2(iris)
#' biplot_ggplot2(iris, "Species")
#' biplot_ggplot2(iris, "Species", ellipse = TRUE, loadings = TRUE)
#' \dontrun
#' dir.create(paste(getwd(), "/examples", sep = ""), showWarnings = FALSE)
#' dir <- paste(getwd(), "/examples/iris", sep = "")
#' biplot_ggplot2(iris,
#'                loadings = FALSE,
#'                title = "Biplot of Iris",
#'                ellipse = TRUE,
#'                out_path = dir)
biplot_ggplot2 <- function(input_df, 
                           groups = "none", 
                           loadings = FALSE, 
                           ellipse = FALSE, 
                           title = "PCA - Biplot", 
                           out_path = "none"){
  
  if(groups == "none"){
    group_by <- NULL
  }
  else {
    group_by <- groups
  }
  
  
  
  biplot <- autoplot(prcomp(dplyr::select_if(input_df, is.numeric)), data = input_df, 
                     colour = group_by, 
                     loadings = loadings,
                     loadings.colour =  "black",
                     loadings.label = loadings,
                     loadings.label.size = 2,
                     loadings.label.colour = "black",
                     frame = ellipse,
                     frame.type = "norm") +
    ggtitle(title) +
    my_theme
  
  if(groups != "none"){
    ellipse_color <- as.vector(viridis(n = length(levels(input_df[[group_by]]))))
    biplot <- biplot + scale_fill_manual(values = ellipse_color) +
      scale_color_manual(values = ellipse_color)
  }
  
  if(out_path != "none"){
    print(paste("Saving plot to ", out_path, "_biplot.png", sep = ""))
    ggsave(paste(out_path, "_biplot.png", sep = ""),
           plot = biplot)
  }  else{
    biplot
  }
}
