my_theme <- theme_set(
  theme_minimal() +
    theme(plot.title = element_text(size=12, hjust = 0.5),
          axis.text.x = element_text(size = 8),
          # axis.title = element_text(size = 10),
          axis.title.x = element_text(size = 10, hjust = 0.5),
          axis.title.y = element_text(size = 10, hjust = 0.5),
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 10))
)

### Principal component analysis

#' Scree plot with factoextra
#'
#' @description `scree_factoextra` takes a prcomp element and diplays the percentage of variance 
#' explained by the principal components in a barplot. 
#' @details This function takes a prcom element (i.e. an element generated by the base::prcomp function), 
#' and displays the percentage of variance explained by each principal component in a barplot. 
#' Additionally there is also a dot- and line graph. 
#' @param prcomp_element object of class prcomp or pca. Produced by base::prcomp or FactoMineR::PCA. 
#' @param out_path string. Path to save plot to png. 
#' If out_path is empty, the plot is printed to the device.
#' @examples 
#' pca_iris <- prcomp(select_if(iris, is.numeric))
#' scree_factoextra(pca_iris, title = "Scree plot iris")
#' \dontrun
#' dir.create(paste(getwd(), "/examples", sep = ""), showWarnings = FALSE)
#' dir <- paste(getwd(), "/examples/iris", sep = "")
#' scree_factoextra(pca_iris, title = "Scree plot iris", out_path = dir)
scree_factoextra <- function(prcomp_element, title = "Scree plot", out_path = "none"){
  
  scree <- fviz_eig(prcomp_element, 
                    barfill = viridis(n = 1, begin = 0.3), 
                    barcolor = viridis(n = 1, begin = 0.3), 
                    # linecolor = "grey40", 
                    addlabels = TRUE) +
    labs(title = title) +
    my_theme # sets general apperance, label size and justification
  
  if(out_path != "none"){
    print(paste("Saving plot to ", out_path, "_screePlot.png", sep = ""))
    ggsave(paste(out_path, "_screePlot.png", sep = ""),
           plot = scree)
  }
  else{
    scree
  }
}

#' Biplot with factorextra
#' 
#' @description `biplot_factoextra` prints a biplot from a prcomp element. 
#' @details This function prints a biplot from a prcomp element. 
#' The points can be colored by group. Loadings are optionally displayed. 
#' @param prcomp_element object of class prcomp. The base::prcomp function performs a principal component analysis. 
#' This is the object it returns. 
#' @param groups vector. Groups to color by. Default = "none"
#' @param ellipse bool. Draw confidence ellipse arount the clusters of groups. Default = FALSE. 
#' @param loadings string / vector of strings. Draw loadings arrows and labels. c("arrow", "text"), "text", "none" (default). 
#' @param out_path string. Path to save plot to png. 
#' If out_path is empty, the plot is printed to the device.
#' @examples 
#' pca_iris <- prcomp(dplyr::select_if(iris, is.numeric))
#' iris_groups <- iris$Species
#' biplot_factoextra(pca_iris)
#' biplot_factoextra(pca_iris, 
#'                   groups = iris_groups, 
#'                   ellipse = TRUE, 
#'                   loadings = c("arrow", "text"))
#' \dontrun
#' dir.create(paste(getwd(), "/examples", sep = ""), showWarnings = FALSE)
#' dir <- paste(getwd(), "/examples/iris", sep = "")
#' biplot_factoextra(pca_iris, 
#'                  groups = iris_groups, 
#'                  ellipse = TRUE, 
#'                  loadings = "none", 
#'                  out_path = dir)
biplot_factoextra <- function(prcomp_element, 
                              groups = "none", 
                              ellipse = FALSE, 
                              loadings = "none", 
                              out_path = "none"){
  
  biplot <- fviz_pca_biplot(prcomp_element, 
                            habillage = groups, # a vector of groups by whicht to color   
                            label = "var", 
                            labelsize = 2,
                            repel = TRUE, # labels do not overlap
                            col.var = "grey40",
                            ## ellipses
                            addEllipses = ellipse, 
                            ellipse.type = "norm",
                            ## legend
                            legend.title = "Groups", 
                            geom.var = loadings)   +
    scale_color_viridis(discrete = TRUE) +
    scale_fill_viridis(discrete = TRUE) +
    my_theme
  
  if(out_path != "none"){
    print(paste("Saving to ", out_path, "_biplot.png", sep = ""))
    ggsave(paste(out_path, "_biplot.png", sep = ""),
           plot = biplot)
  }
  else{
    biplot
  }
}


#' Scree plot with Rbase
#'
#' @description `scree_base` takes a prcomp element and diplays the percentage and the cummulative percentage of variance of variance 
#' explained by the principal components in a barplot. 
#' @details This function takes a prcomp element (i.e. an element generated by the base::prcomp function), 
#' and displays the percentage of variance and the cummulative percentage of variance explained by each principal component in a dot- and line graph. 
#' @param input_df data frame or matrix. 
#' @scale bool. Apply scaling when erforming PCA. Default = FALSE. 
#' @param out_path string. Path to save plot to png. 
#' If out_path is empty, the plot is printed to the device.
#' @examples 
#' scree_base(mtcars)
#' \dontrun
#' dir.create(paste(getwd(), "/examples", sep = ""), showWarnings = FALSE)
#' dir <- paste(getwd(), "/examples/iris", sep = "")
#' scree_base(mtcars, out_path = dir)
scree_base <- function(input_df, 
                       title = c("Scree plot", "Cummulative scree plot"), 
                       scale = FALSE,
                       out_path = "none"){
  
  out_name <- paste(out_path, "_screePlot", ".png", sep = "")
  
  prcomp_element <- prcomp(input_df)
  
  # variance explained by each pc
  var_pca <- prcomp_element$sdev ^ 2
  prop_of_variance <- round(var_pca / sum(var_pca), 5) * 100
  cummulative_prop_of_variance <- cumsum(prop_of_variance)
  proportion_of_variance_table <- data.frame(Proportion_of_variance = prop_of_variance, 
                                             Cummulative_proportion_of_variance = cummulative_prop_of_variance)
  
  func <- function(){
    par(mfrow=c(1,2), mar = c(2, 2, 2, 2))
    plot(prop_of_variance, # scree plot to decide which PCs are used
         main = "", xlab ="", ylab ="",
         ylim=c(0 ,100),
         type = "b")
    title( main = title[1], cex.main = 0.9, font.main = 1, 
           cex.lab = 1, 
           xlab =" Principal Component ", 
           ylab =" Proportion of Variance Explained [%]")
    
    plot(cummulative_prop_of_variance, # scree plot to decide which PCs are used
         main = "", xlab ="", ylab ="",
         ylim=c(0 ,100),
         type="b")
    title( main = title[2], cex.main = 0.9, font.main = 1, 
           cex.lab = 0.8, 
           xlab ="Principal Component",
           ylab ="Cumulative Proportion of Variance Explained [%]")
  }
  
  if(out_path != "none"){
    print(paste("Saving to ", out_name))
    png(filename = out_name)
    func()
    dev.off()
  }
  else{
    func()
  }
}


#' Biplot with ggplot2
#' 
#' @description `biplot_ggplot2` prints a biplot from a prcomp element. 
#' @details This function prints a biplot from a prcomp element. 
#' The points can be colored by group. Loadings are optionally displayed. 
#' @param input_df a data frame with at least one factor column. 
#' @param groups vector. Groups to color by. Default = "none"
#' @param ellipse logical. Draw confidence ellipse arount the clusters of groups. Default = FALSE. 
#' @param loadings logical. Draw loadings arrows and labels. Default = FALSE
#' @param out_path string. Path to save plot to png. 
#' If out_path is empty, the plot is printed to the device.
#' @examples 
#' biplot_ggplot2(iris)
#' biplot_ggplot2(iris, "Species")
#' biplot_ggplot2(iris, "Species", ellipse = TRUE, loadings = TRUE)
#' \dontrun
#' dir.create(paste(getwd(), "/examples", sep = ""), showWarnings = FALSE)
#' dir <- paste(getwd(), "/examples/iris", sep = "")
#' biplot_ggplot2(iris,
#'                loadings = FALSE,
#'                title = "Biplot of Iris",
#'                ellipse = TRUE,
#'                out_path = dir)
biplot_ggplot2 <- function(input_df, 
                           groups = "none", 
                           scale = FALSE,
                           loadings = FALSE, 
                           ellipse = FALSE, 
                           title = "PCA - Biplot", 
                           out_path = "none"){
  
  if(groups == "none"){
    group_by <- NULL
  }
  else {
    group_by <- groups
  }
  
  prcomp_element <- prcomp(select_if(input_df, is.numeric), scale. = scale)
  
  biplot <- autoplot(prcomp_element, data = input_df, 
                     colour = group_by, 
                     loadings = loadings,
                     loadings.colour =  "black",
                     loadings.label = loadings,
                     loadings.label.size = 2,
                     loadings.label.colour = "black",
                     frame = ellipse,
                     frame.type = "norm") +
    ggtitle(title) +
    my_theme
  
  if(groups != "none"){
    group_color <- as.vector(viridis(n = length(levels(input_df[[group_by]])), alpha = 1))
    biplot <- biplot + 
      scale_fill_manual(values = group_color) +
      scale_color_manual(values = group_color)
  }
  
  if(out_path != "none"){
    print(paste("Saving plot to ", out_path, "_biplot.png", sep = ""))
    ggsave(paste(out_path, "_biplot.png", sep = ""),
           plot = biplot)
  }  else{
    biplot
  }
}

#' Plot contribution to pca
#' 
#' `plot_contrib_to_pc` plots the contributions of each variable to each principal component in a grid. 
#' @param pca_element Object produced by FactoMineR::PCA. 
#' @param title string. Main title of the plot. Default = "Contribution of variables to the principal components"
#' @param out_path string. Path to save plot as png. If "none" (default), plot is printed to device. 
#' @example 
#' cars_pca <- PCA(select_if(mtcars, is.numeric), graph = FALSE)
#' plot_contrib_to_pc(cars_pca)
plot_contrib_to_pc <- function(pca_element,
                               title = "Contribution of variables to the principal components", 
                               out_path = "none"){
  
  out_name = paste(out_path, "pca_contribution")
  
  pca_variables <- get_pca_var(pca_element)
  pca_contrib <- as.data.frame(pca_variables$contrib)
  pca_contrib_ordered <- pca_contrib[order(pca_contrib$Dim.1, decreasing = TRUE),]
  
  func <- function(){
    
    par(mar = c(1, 1, 10, 1), mfrow = c(1, 1), family = "AvantGarde", col.main = "grey40", cex.main = 0.8, col.axis = "grey40")
    mycolors <- as.vector(viridis(n = 10, direction = -1))
    corrplot(t(pca_contrib_ordered), 
             method = "circle",
             is.corr = FALSE,
             pch.col = "green", 
             tl.srt = 45, 
             tl.cex = 0.5, 
             tl.col = "grey40",
             col= colorRampPalette(mycolors)(10), 
             cl.cex = 0.5, 
             cl.align.text = "l"
    )
    title(main = title)
  }
  
  if(out_path != "none"){
    print(paste("Saving to ", out_name))
    png(filename = out_name, width = 15*96, height = 5*96, units = "px")
    func()
    dev.off()
  }
  else{
    func()
  }
  par(mar = c(1, 1, 1, 1))
}

#' Loadings plot
#' 
#' `plot_loadings` plots the loadings between the first two principal components. 
#' @param pca_object Object produced by FactoMineR::PCA. 
#' @param title string. Main title of the plot. Default = "Loadings plot"
#' @param colour logical. TRUE ... color scale by PC1. FALSE (default) ... all black. 
#' @param top_loadings integer. Number of loadings to label (the top n loadings of both PCs are labelled).
#' @param out_path string. Path to save plot as png. If "none" (default), plot is only printed to device. 
#' @example 
#' cars_pca <- PCA(select_if(mtcars, is.numeric), graph = FALSE)
#' plot_contrib_to_pc(cars_pca)
plot_loadings <- function(pca_object, 
                          colour = FALSE,
                          top_loadings = 10,
                          title = "Loadings plot", 
                          out_path = "none"){
  x <- pca_object$var
  loadings <- as.data.frame(x$coord)
  loadings <- data.frame(loadings, x$contrib)
  
  loadings$mylabel <- rep("", nrow(loadings))
  loadings <- loadings[order(loadings$Dim.1.1, decreasing = TRUE),]
  loadings$mylabel[1:10] <- rownames(loadings)[1:10]
  loadings <- loadings[order(loadings$Dim.2.1, decreasing = TRUE),]
  loadings$mylabel[1:top_loadings] <- rownames(loadings)[1:top_loadings]
  
  if(top_loadings == 0){
    loadings$mylabel <- rep("", nrow(loadings))
  }

  if(colour == TRUE){
  loadings_plot <- ggplot(loadings, aes(x=Dim.1, 
                                        y=Dim.2, 
                                        colour = Dim.1.1))  }
  else{ loadings_plot <- ggplot(loadings, aes(x=Dim.1, 
                                              y=Dim.2))  }
  
  loadings_plot <- loadings_plot + 
    geom_point(size=1) +
    geom_hline(yintercept = 0,
               linetype = "dashed",
               colour = "grey60") +
    geom_vline(xintercept = 0,
               linetype = "dashed",
               colour = "grey60") +
    geom_text_repel(aes(x = Dim.1,
                        y = Dim.2,
                        label = mylabel),
                    colour = "black",
                    size = 2) +
    ggtitle(label = title) +
    scale_color_viridis_c(direction = -1, end = 0.9) +
    my_theme
  
  
  if(out_path != "none"){
    print(paste("Saving plot to ", out_path, "_biplot.png", sep = ""))
    ggsave(paste(out_path, "_loadings_plot.png", sep = ""),
           plot = loadings_plot)
  }
  
  loadings_plot
}
